name: Build and Test
on:
  push:
    branches:
      - develop # Your default release branch
jobs:
 test: 
  runs-on: Test on node ${{ matrix.node }} and ${{ matrix.os }}
  strategy:
      matrix:
        node: [8, 12]
        os: [ubuntu-latest, windows-latest]
  name: Build and Test
  steps: 
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    - run: dotnet build AkkaSim/AkkaSim.csproj
    - run: dotnet test TestAkkaSim/TestAkkaSim.csproj